//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFilters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFilters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceFilters", typeof(ResourceFilters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string allSelected {
            get {
                return ResourceManager.GetString("allSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по конвейерным весам.
        /// </summary>
        public static string Belt {
            get {
                return ResourceManager.GetString("Belt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за сутки.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат отчета.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по распроложению.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта.
        /// </summary>
        public static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за месяц.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрано.
        /// </summary>
        public static string NonSelected {
            get {
                return ResourceManager.GetString("NonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано.
        /// </summary>
        public static string nSelected {
            get {
                return ResourceManager.GetString("nSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период отчета.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за квартал.
        /// </summary>
        public static string Quater {
            get {
                return ResourceManager.GetString("Quater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по конвейерным весам.
        /// </summary>
        public static string ReportBelt {
            get {
                return ResourceManager.GetString("ReportBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по скиповым подъемам.
        /// </summary>
        public static string ReportSkip {
            get {
                return ResourceManager.GetString("ReportSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по вагонным весам.
        /// </summary>
        public static string ReportWagon {
            get {
                return ResourceManager.GetString("ReportWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрано.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по скипам.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по дате.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to по.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип отчета.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по вагонным весам.
        /// </summary>
        public static string Wagon {
            get {
                return ResourceManager.GetString("Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за неделю.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за год.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
