//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGeneral() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceGeneral", typeof(ResourceGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string DateRangePickerApplyLabel {
            get {
                return ResourceManager.GetString("DateRangePickerApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель.
        /// </summary>
        public static string DateRangePickerApr {
            get {
                return ResourceManager.GetString("DateRangePickerApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авгутс.
        /// </summary>
        public static string DateRangePickerAug {
            get {
                return ResourceManager.GetString("DateRangePickerAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string DateRangePickerCancelLabel {
            get {
                return ResourceManager.GetString("DateRangePickerCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свой интервал.
        /// </summary>
        public static string DateRangePickerCustomRangeLabel {
            get {
                return ResourceManager.GetString("DateRangePickerCustomRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь.
        /// </summary>
        public static string DateRangePickerDec {
            get {
                return ResourceManager.GetString("DateRangePickerDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль.
        /// </summary>
        public static string DateRangePickerFeb {
            get {
                return ResourceManager.GetString("DateRangePickerFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string DateRangePickerFromLabel {
            get {
                return ResourceManager.GetString("DateRangePickerFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь.
        /// </summary>
        public static string DateRangePickerJan {
            get {
                return ResourceManager.GetString("DateRangePickerJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль.
        /// </summary>
        public static string DateRangePickerJul {
            get {
                return ResourceManager.GetString("DateRangePickerJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь.
        /// </summary>
        public static string DateRangePickerJun {
            get {
                return ResourceManager.GetString("DateRangePickerJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март.
        /// </summary>
        public static string DateRangePickerMar {
            get {
                return ResourceManager.GetString("DateRangePickerMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май.
        /// </summary>
        public static string DateRangePickerMay {
            get {
                return ResourceManager.GetString("DateRangePickerMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь.
        /// </summary>
        public static string DateRangePickerNov {
            get {
                return ResourceManager.GetString("DateRangePickerNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрь.
        /// </summary>
        public static string DateRangePickerOct {
            get {
                return ResourceManager.GetString("DateRangePickerOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь.
        /// </summary>
        public static string DateRangePickerSep {
            get {
                return ResourceManager.GetString("DateRangePickerSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string DateRangePickerToLabel {
            get {
                return ResourceManager.GetString("DateRangePickerToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно быть заполнено.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система учета угля.
        /// </summary>
        public static string HeadeaAppCaption {
            get {
                return ResourceManager.GetString("HeadeaAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аналитика.
        /// </summary>
        public static string HeaderAppName {
            get {
                return ResourceManager.GetString("HeaderAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рус / Eng.
        /// </summary>
        public static string HeaderLanguageChoose {
            get {
                return ResourceManager.GetString("HeaderLanguageChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string HeaderLanguageEng {
            get {
                return ResourceManager.GetString("HeaderLanguageEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string HeaderLanguageRus {
            get {
                return ResourceManager.GetString("HeaderLanguageRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная панель управления.
        /// </summary>
        public static string HeaderMainPageName {
            get {
                return ResourceManager.GetString("HeaderMainPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string HeaderTabAbout {
            get {
                return ResourceManager.GetString("HeaderTabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвейерные.
        /// </summary>
        public static string HeaderTabBelt {
            get {
                return ResourceManager.GetString("HeaderTabBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сводные.
        /// </summary>
        public static string HeaderTabConsolidated {
            get {
                return ResourceManager.GetString("HeaderTabConsolidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string HeaderTabContacts {
            get {
                return ResourceManager.GetString("HeaderTabContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дашбоарды.
        /// </summary>
        public static string HeaderTabDashboard {
            get {
                return ResourceManager.GetString("HeaderTabDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамические.
        /// </summary>
        public static string HeaderTabDynamic {
            get {
                return ResourceManager.GetString("HeaderTabDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По оборудованию.
        /// </summary>
        public static string HeaderTabEquipment {
            get {
                return ResourceManager.GetString("HeaderTabEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта.
        /// </summary>
        public static string HeaderTabMap {
            get {
                return ResourceManager.GetString("HeaderTabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мнемосхемы.
        /// </summary>
        public static string HeaderTabMnemo {
            get {
                return ResourceManager.GetString("HeaderTabMnemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string HeaderTabReports {
            get {
                return ResourceManager.GetString("HeaderTabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скипы.
        /// </summary>
        public static string HeaderTabSkip {
            get {
                return ResourceManager.GetString("HeaderTabSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статические.
        /// </summary>
        public static string HeaderTabStatic {
            get {
                return ResourceManager.GetString("HeaderTabStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагонные.
        /// </summary>
        public static string HeaderTabWagon {
            get {
                return ResourceManager.GetString("HeaderTabWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОЛЬЗОВАТЕЛЬ:.
        /// </summary>
        public static string HeaderUserCaption {
            get {
                return ResourceManager.GetString("HeaderUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прошлый месяц.
        /// </summary>
        public static string PrevMonth {
            get {
                return ResourceManager.GetString("PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот месяц.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот квартал.
        /// </summary>
        public static string ThisQuater {
            get {
                return ResourceManager.GetString("ThisQuater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта неделя.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот год.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вчера.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
