//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceGeneral", typeof(ResourceGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string DateRangePickerApplyLabel {
            get {
                return ResourceManager.GetString("DateRangePickerApplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апрель.
        /// </summary>
        public static string DateRangePickerApr {
            get {
                return ResourceManager.GetString("DateRangePickerApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авгутс.
        /// </summary>
        public static string DateRangePickerAug {
            get {
                return ResourceManager.GetString("DateRangePickerAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string DateRangePickerCancelLabel {
            get {
                return ResourceManager.GetString("DateRangePickerCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свой интервал.
        /// </summary>
        public static string DateRangePickerCustomRangeLabel {
            get {
                return ResourceManager.GetString("DateRangePickerCustomRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Декабрь.
        /// </summary>
        public static string DateRangePickerDec {
            get {
                return ResourceManager.GetString("DateRangePickerDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Февраль.
        /// </summary>
        public static string DateRangePickerFeb {
            get {
                return ResourceManager.GetString("DateRangePickerFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пт.
        /// </summary>
        public static string DateRangePickerFr {
            get {
                return ResourceManager.GetString("DateRangePickerFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string DateRangePickerFromLabel {
            get {
                return ResourceManager.GetString("DateRangePickerFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Январь.
        /// </summary>
        public static string DateRangePickerJan {
            get {
                return ResourceManager.GetString("DateRangePickerJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июль.
        /// </summary>
        public static string DateRangePickerJul {
            get {
                return ResourceManager.GetString("DateRangePickerJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Июнь.
        /// </summary>
        public static string DateRangePickerJun {
            get {
                return ResourceManager.GetString("DateRangePickerJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Март.
        /// </summary>
        public static string DateRangePickerMar {
            get {
                return ResourceManager.GetString("DateRangePickerMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Май.
        /// </summary>
        public static string DateRangePickerMay {
            get {
                return ResourceManager.GetString("DateRangePickerMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пн.
        /// </summary>
        public static string DateRangePickerMo {
            get {
                return ResourceManager.GetString("DateRangePickerMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноябрь.
        /// </summary>
        public static string DateRangePickerNov {
            get {
                return ResourceManager.GetString("DateRangePickerNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Октябрь.
        /// </summary>
        public static string DateRangePickerOct {
            get {
                return ResourceManager.GetString("DateRangePickerOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сб.
        /// </summary>
        public static string DateRangePickerSa {
            get {
                return ResourceManager.GetString("DateRangePickerSa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сентябрь.
        /// </summary>
        public static string DateRangePickerSep {
            get {
                return ResourceManager.GetString("DateRangePickerSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вс.
        /// </summary>
        public static string DateRangePickerSu {
            get {
                return ResourceManager.GetString("DateRangePickerSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чт.
        /// </summary>
        public static string DateRangePickerTh {
            get {
                return ResourceManager.GetString("DateRangePickerTh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string DateRangePickerToLabel {
            get {
                return ResourceManager.GetString("DateRangePickerToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вт.
        /// </summary>
        public static string DateRangePickerTu {
            get {
                return ResourceManager.GetString("DateRangePickerTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ср.
        /// </summary>
        public static string DateRangePickerWe {
            get {
                return ResourceManager.GetString("DateRangePickerWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно быть заполнено.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система учета угля.
        /// </summary>
        public static string HeadeaAppCaption {
            get {
                return ResourceManager.GetString("HeadeaAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика.
        /// </summary>
        public static string HeaderAppName {
            get {
                return ResourceManager.GetString("HeaderAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рус / Eng.
        /// </summary>
        public static string HeaderLanguageChoose {
            get {
                return ResourceManager.GetString("HeaderLanguageChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string HeaderLanguageEng {
            get {
                return ResourceManager.GetString("HeaderLanguageEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string HeaderLanguageRus {
            get {
                return ResourceManager.GetString("HeaderLanguageRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная панель управления.
        /// </summary>
        public static string HeaderMainPageName {
            get {
                return ResourceManager.GetString("HeaderMainPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string HeaderTabAbout {
            get {
                return ResourceManager.GetString("HeaderTabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвейерные.
        /// </summary>
        public static string HeaderTabBelt {
            get {
                return ResourceManager.GetString("HeaderTabBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводные.
        /// </summary>
        public static string HeaderTabConsolidated {
            get {
                return ResourceManager.GetString("HeaderTabConsolidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string HeaderTabContacts {
            get {
                return ResourceManager.GetString("HeaderTabContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дашбоарды.
        /// </summary>
        public static string HeaderTabDashboard {
            get {
                return ResourceManager.GetString("HeaderTabDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Динамические.
        /// </summary>
        public static string HeaderTabDynamic {
            get {
                return ResourceManager.GetString("HeaderTabDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По оборудованию.
        /// </summary>
        public static string HeaderTabEquipment {
            get {
                return ResourceManager.GetString("HeaderTabEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string HeaderTabMap {
            get {
                return ResourceManager.GetString("HeaderTabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мнемосхемы.
        /// </summary>
        public static string HeaderTabMnemo {
            get {
                return ResourceManager.GetString("HeaderTabMnemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string HeaderTabReports {
            get {
                return ResourceManager.GetString("HeaderTabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скипы.
        /// </summary>
        public static string HeaderTabSkip {
            get {
                return ResourceManager.GetString("HeaderTabSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статические.
        /// </summary>
        public static string HeaderTabStatic {
            get {
                return ResourceManager.GetString("HeaderTabStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонные.
        /// </summary>
        public static string HeaderTabWagon {
            get {
                return ResourceManager.GetString("HeaderTabWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОЛЬЗОВАТЕЛЬ:.
        /// </summary>
        public static string HeaderUserCaption {
            get {
                return ResourceManager.GetString("HeaderUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прошлый месяц.
        /// </summary>
        public static string PrevMonth {
            get {
                return ResourceManager.GetString("PrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот месяц.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот квартал.
        /// </summary>
        public static string ThisQuater {
            get {
                return ResourceManager.GetString("ThisQuater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта неделя.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот год.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вчера.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
