//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMnemonic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMnemonic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceMnemonic", typeof(ResourceMnemonic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Абайская.
        /// </summary>
        public static string AbayMineName {
            get {
                return ResourceManager.GetString("AbayMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акт.
        /// </summary>
        public static string Act {
            get {
                return ResourceManager.GetString("Act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прибыло.
        /// </summary>
        public static string Arrived {
            get {
                return ResourceManager.GetString("Arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелка.
        /// </summary>
        public static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На складе.
        /// </summary>
        public static string AtStockPiles {
            get {
                return ResourceManager.GetString("AtStockPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные полученные автоматически.
        /// </summary>
        public static string AutomaticData {
            get {
                return ResourceManager.GetString("AutomaticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал конвейерных весов.
        /// </summary>
        public static string BeltScaleJournal {
            get {
                return ResourceManager.GetString("BeltScaleJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котельная.
        /// </summary>
        public static string BoilderPlant {
            get {
                return ResourceManager.GetString("BoilderPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Котельные.
        /// </summary>
        public static string BoilerButton {
            get {
                return ResourceManager.GetString("BoilerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено угля.
        /// </summary>
        public static string BoilerConsumptionFact {
            get {
                return ResourceManager.GetString("BoilerConsumptionFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Норма потребления.
        /// </summary>
        public static string BoilerConsumptionNorm {
            get {
                return ResourceManager.GetString("BoilerConsumptionNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормы потребления котельных.
        /// </summary>
        public static string BoilerNorm {
            get {
                return ResourceManager.GetString("BoilerNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брутто.
        /// </summary>
        public static string Brutto {
            get {
                return ResourceManager.GetString("Brutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеонаблюдение.
        /// </summary>
        public static string Cctv {
            get {
                return ResourceManager.GetString("Cctv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уголь.
        /// </summary>
        public static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено за смену.
        /// </summary>
        public static string CoalFromCrushingMachinePerShift {
            get {
                return ResourceManager.GetString("CoalFromCrushingMachinePerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Весы норма.
        /// </summary>
        public static string CoalNormal {
            get {
                return ResourceManager.GetString("CoalNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добыто угля (тонн):.
        /// </summary>
        public static string CoalProduced {
            get {
                return ResourceManager.GetString("CoalProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостача угля.
        /// </summary>
        public static string CoalWarning {
            get {
                return ResourceManager.GetString("CoalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЦОФ.
        /// </summary>
        public static string COF {
            get {
                return ResourceManager.GetString("COF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЦОФ Восточная.
        /// </summary>
        public static string CofName {
            get {
                return ResourceManager.GetString("CofName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произведено концентрата (тонн):.
        /// </summary>
        public static string ConcentrateProduced {
            get {
                return ResourceManager.GetString("ConcentrateProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ушло концентрата.
        /// </summary>
        public static string ConcentrateShipped {
            get {
                return ResourceManager.GetString("ConcentrateShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвейер.
        /// </summary>
        public static string Conveyor {
            get {
                return ResourceManager.GetString("Conveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвейерные весы.
        /// </summary>
        public static string Conveyors_many {
            get {
                return ResourceManager.GetString("Conveyors-many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздробл. на смену.
        /// </summary>
        public static string CrushedPerShift {
            get {
                return ResourceManager.GetString("CrushedPerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дробильная установка.
        /// </summary>
        public static string Crusher {
            get {
                return ResourceManager.GetString("Crusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дробильная установка.
        /// </summary>
        public static string CrushingMachine {
            get {
                return ResourceManager.GetString("CrushingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дней без нарушений ТБ:.
        /// </summary>
        public static string DaysWithoutHse {
            get {
                return ResourceManager.GetString("DaysWithoutHse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дд:чч:мм.
        /// </summary>
        public static string DDHHmm {
            get {
                return ResourceManager.GetString("DDHHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оборудоавние.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чч:мм.
        /// </summary>
        public static string HHmm {
            get {
                return ResourceManager.GetString("HHmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инцидент ТБ.
        /// </summary>
        public static string HSEWarning {
            get {
                return ResourceManager.GetString("HSEWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество инцидентов.
        /// </summary>
        public static string IncidentCount {
            get {
                return ResourceManager.GetString("IncidentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инциденты.
        /// </summary>
        public static string Incidents {
            get {
                return ResourceManager.GetString("Incidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница на этапе разработки.
        /// </summary>
        public static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Казахстанская.
        /// </summary>
        public static string KazMineName {
            get {
                return ResourceManager.GetString("KazMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ст. Драмтеатр.
        /// </summary>
        public static string Kost_raspozn1 {
            get {
                return ResourceManager.GetString("Kost_raspozn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выезд.
        /// </summary>
        public static string Kost_raspozn2 {
            get {
                return ResourceManager.GetString("Kost_raspozn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта им. Костенко.
        /// </summary>
        public static string KostMineName {
            get {
                return ResourceManager.GetString("KostMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бункер для котельной.
        /// </summary>
        public static string KotelBunker {
            get {
                return ResourceManager.GetString("KotelBunker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пути КТЖ.
        /// </summary>
        public static string KtzhWays {
            get {
                return ResourceManager.GetString("KtzhWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта им. Кузембаева.
        /// </summary>
        public static string KuzMineName {
            get {
                return ResourceManager.GetString("KuzMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посл. скип время.
        /// </summary>
        public static string LastLoadedSkip {
            get {
                return ResourceManager.GetString("LastLoadedSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посл. скип день.
        /// </summary>
        public static string LastLoadedSkipDay {
            get {
                return ResourceManager.GetString("LastLoadedSkipDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка посл. скипа.
        /// </summary>
        public static string LastSkipStopTime {
            get {
                return ResourceManager.GetString("LastSkipStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний состав.
        /// </summary>
        public static string LastTrain {
            get {
                return ResourceManager.GetString("LastTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление посл. сост..
        /// </summary>
        public static string LastTrainDirection {
            get {
                return ResourceManager.GetString("LastTrainDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посл. загруж. состав.
        /// </summary>
        public static string LastTrainLoadingTime {
            get {
                return ResourceManager.GetString("LastTrainLoadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посл.состав.
        /// </summary>
        public static string LastTrainLoadingTimeShort {
            get {
                return ResourceManager.GetString("LastTrainLoadingTimeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условные обозначения.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта им. Ленина.
        /// </summary>
        public static string LenMineName {
            get {
                return ResourceManager.GetString("LenMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Весы.
        /// </summary>
        public static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подъем.
        /// </summary>
        public static string LiftingID {
            get {
                return ResourceManager.GetString("LiftingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загруж. в посл. состав.
        /// </summary>
        public static string LoadedAtLastTrain {
            get {
                return ResourceManager.GetString("LoadedAtLastTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружено за смену.
        /// </summary>
        public static string LoadedPerShift {
            get {
                return ResourceManager.GetString("LoadedPerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес партии.
        /// </summary>
        public static string LotQuantity {
            get {
                return ResourceManager.GetString("LotQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные полученные с ручного ввода.
        /// </summary>
        public static string ManuaData {
            get {
                return ResourceManager.GetString("ManuaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ручной ввод.
        /// </summary>
        public static string ManualInput {
            get {
                return ResourceManager.GetString("ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр только по ручному вводу.
        /// </summary>
        public static string ManualInputFilter {
            get {
                return ResourceManager.GetString("ManualInputFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ручной ввод.
        /// </summary>
        public static string ManualInputToolTip {
            get {
                return ResourceManager.GetString("ManualInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string MapButton {
            get {
                return ResourceManager.GetString("MapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта GPS.
        /// </summary>
        public static string MapGpsButton {
            get {
                return ResourceManager.GetString("MapGpsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта.
        /// </summary>
        public static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схема.
        /// </summary>
        public static string MnemonicButton {
            get {
                return ResourceManager.GetString("MnemonicButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нетто.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных за период.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string OpenSkipAct {
            get {
                return ResourceManager.GetString("OpenSkipAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по возрастанию времени.
        /// </summary>
        public static string OrderByTransferTimeStampAsc {
            get {
                return ResourceManager.GetString("OrderByTransferTimeStampAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № заказа.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За период.
        /// </summary>
        public static string PerPeriod {
            get {
                return ResourceManager.GetString("PerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За смену.
        /// </summary>
        public static string PerShift {
            get {
                return ResourceManager.GetString("PerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to шт..
        /// </summary>
        public static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to План/факт.
        /// </summary>
        public static string PlanFact {
            get {
                return ResourceManager.GetString("PlanFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ушло пром.продукта.
        /// </summary>
        public static string PprodShipped {
            get {
                return ResourceManager.GetString("PprodShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произв. за период.
        /// </summary>
        public static string ProdFact {
            get {
                return ResourceManager.GetString("ProdFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произв.план.
        /// </summary>
        public static string ProdPlan {
            get {
                return ResourceManager.GetString("ProdPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произв. за смену.
        /// </summary>
        public static string ProductionPerShift {
            get {
                return ResourceManager.GetString("ProductionPerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Производительность (тонн/чел.).
        /// </summary>
        public static string Productivity {
            get {
                return ResourceManager.GetString("Productivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция.
        /// </summary>
        public static string RailRoadStaion {
            get {
                return ResourceManager.GetString("RailRoadStaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распознано номеров.
        /// </summary>
        public static string RecognintionRate {
            get {
                return ResourceManager.GetString("RecognintionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распознавание.
        /// </summary>
        public static string Recognition {
            get {
                return ResourceManager.GetString("Recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал распознавания вагонов.
        /// </summary>
        public static string RecognitionJourlal {
            get {
                return ResourceManager.GetString("RecognitionJourlal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распознан.
        /// </summary>
        public static string Recognized {
            get {
                return ResourceManager.GetString("Recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Породный бункер.
        /// </summary>
        public static string RockBunker {
            get {
                return ResourceManager.GetString("RockBunker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порода.
        /// </summary>
        public static string Rocks {
            get {
                return ResourceManager.GetString("Rocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Породы за период.
        /// </summary>
        public static string RocksFromCrushingPerPeriod {
            get {
                return ResourceManager.GetString("RocksFromCrushingPerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Породы за сутки.
        /// </summary>
        public static string RocksFromCrushingPerShift {
            get {
                return ResourceManager.GetString("RocksFromCrushingPerShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утилизация породы.
        /// </summary>
        public static string RocksUtilization {
            get {
                return ResourceManager.GetString("RocksUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Саранская-1.
        /// </summary>
        public static string Sar1MineName {
            get {
                return ResourceManager.GetString("Sar1MineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выезд Запад.
        /// </summary>
        public static string Sar3_raspozn1 {
            get {
                return ResourceManager.GetString("Sar3_raspozn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выезд Восток.
        /// </summary>
        public static string Sar3_raspozn2 {
            get {
                return ResourceManager.GetString("Sar3_raspozn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Саранская-3.
        /// </summary>
        public static string Sar3MineName {
            get {
                return ResourceManager.GetString("Sar3MineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Саранская.
        /// </summary>
        public static string SarMineName {
            get {
                return ResourceManager.GetString("SarMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Шахтинская.
        /// </summary>
        public static string ShahMineName {
            get {
                return ResourceManager.GetString("ShahMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отгружено.
        /// </summary>
        public static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ушло.
        /// </summary>
        public static string ShippedShort {
            get {
                return ResourceManager.GetString("ShippedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скиповой подъем.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скипы.
        /// </summary>
        public static string Skip_many {
            get {
                return ResourceManager.GetString("Skip-many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to скипов.
        /// </summary>
        public static string Skips {
            get {
                return ResourceManager.GetString("Skips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал подъемов.
        /// </summary>
        public static string SkipsLiftingJournal {
            get {
                return ResourceManager.GetString("SkipsLiftingJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер приказа.
        /// </summary>
        public static string SkipWeightOrderNo {
            get {
                return ResourceManager.GetString("SkipWeightOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акты перевески скипов.
        /// </summary>
        public static string SkipWeights {
            get {
                return ResourceManager.GetString("SkipWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действителен с.
        /// </summary>
        public static string SkipWeightVaildFrom {
            get {
                return ResourceManager.GetString("SkipWeightVaildFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция Абай.
        /// </summary>
        public static string StAbayName {
            get {
                return ResourceManager.GetString("StAbayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено.
        /// </summary>
        public static string StationIncome {
            get {
                return ResourceManager.GetString("StationIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено.
        /// </summary>
        public static string StationOutcome {
            get {
                return ResourceManager.GetString("StationOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция Дубовская.
        /// </summary>
        public static string StDubovName {
            get {
                return ResourceManager.GetString("StDubovName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытый склад.
        /// </summary>
        public static string Stockpile {
            get {
                return ResourceManager.GetString("Stockpile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свободно.
        /// </summary>
        public static string StockpileFree {
            get {
                return ResourceManager.GetString("StockpileFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено за период.
        /// </summary>
        public static string StockpileIncome {
            get {
                return ResourceManager.GetString("StockpileIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал склада.
        /// </summary>
        public static string StockPileJournal {
            get {
                return ResourceManager.GetString("StockPileJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее кол-во угля.
        /// </summary>
        public static string StockPileTotal {
            get {
                return ResourceManager.GetString("StockPileTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ст. Распорядительная.
        /// </summary>
        public static string StRasporName {
            get {
                return ResourceManager.GetString("StRasporName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Станция Углерудная.
        /// </summary>
        public static string StUglerudName {
            get {
                return ResourceManager.GetString("StUglerudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техника.
        /// </summary>
        public static string Technika {
            get {
                return ResourceManager.GetString("Technika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Тентекская.
        /// </summary>
        public static string TentMineName {
            get {
                return ResourceManager.GetString("TentMineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник.
        /// </summary>
        public static string Thesaurus {
            get {
                return ResourceManager.GetString("Thesaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тонн.
        /// </summary>
        public static string Tonns {
            get {
                return ResourceManager.GetString("Tonns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to т/день.
        /// </summary>
        public static string TonnsPerDay {
            get {
                return ResourceManager.GetString("TonnsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий вес.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего вагонов.
        /// </summary>
        public static string TotalWagons {
            get {
                return ResourceManager.GetString("TotalWagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер состава.
        /// </summary>
        public static string TrainNumber {
            get {
                return ResourceManager.GetString("TrainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонов в посл.сост..
        /// </summary>
        public static string WagonAtLastTrain {
            get {
                return ResourceManager.GetString("WagonAtLastTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во вагонов посл. сост.
        /// </summary>
        public static string WagonCountAtLastTrain {
            get {
                return ResourceManager.GetString("WagonCountAtLastTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка вагона.
        /// </summary>
        public static string WagonLoading {
            get {
                return ResourceManager.GetString("WagonLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Журнал загрузки вагонов.
        /// </summary>
        public static string WagonLoadingJourlal {
            get {
                return ResourceManager.GetString("WagonLoadingJourlal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № вагона.
        /// </summary>
        public static string WagonNumber {
            get {
                return ResourceManager.GetString("WagonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр по номеру вагона.
        /// </summary>
        public static string WagonNumberFilter {
            get {
                return ResourceManager.GetString("WagonNumberFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонов.
        /// </summary>
        public static string Wagons {
            get {
                return ResourceManager.GetString("Wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонные весы.
        /// </summary>
        public static string WagonScales_many {
            get {
                return ResourceManager.GetString("WagonScales-many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск вагона.
        /// </summary>
        public static string WagonSearch {
            get {
                return ResourceManager.GetString("WagonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прошло вагонов.
        /// </summary>
        public static string WagonsPassed {
            get {
                return ResourceManager.GetString("WagonsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес, т.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагонные весы.
        /// </summary>
        public static string WeightBriges {
            get {
                return ResourceManager.GetString("WeightBriges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соответствие.
        /// </summary>
        public static string WeightConclusionGood {
            get {
                return ResourceManager.GetString("WeightConclusionGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В 1 составе.
        /// </summary>
        public static string WeightConclusionIn1Train {
            get {
                return ResourceManager.GetString("WeightConclusionIn1Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За интервал.
        /// </summary>
        public static string WeightConclusionWeightPerPeriod {
            get {
                return ResourceManager.GetString("WeightConclusionWeightPerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несоответствие.
        /// </summary>
        public static string WeithConclustionBad {
            get {
                return ResourceManager.GetString("WeithConclustionBad", resourceCulture);
            }
        }
    }
}
