//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStatic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStatic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceStatic", typeof(ResourceStatic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по алармам.
        /// </summary>
        public static string AlarmReport {
            get {
                return ResourceManager.GetString("AlarmReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по конвейерным весам.
        /// </summary>
        public static string BeltScalesReport {
            get {
                return ResourceManager.GetString("BeltScalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по добыче угля по шахтам за месяц.
        /// </summary>
        public static string CoalProductionByMine {
            get {
                return ResourceManager.GetString("CoalProductionByMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение данных по добыче Опер. учет и CTS.
        /// </summary>
        public static string ComparisonInfoMiningsReport {
            get {
                return ResourceManager.GetString("ComparisonInfoMiningsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет за день.
        /// </summary>
        public static string ConsolidatedDaily {
            get {
                return ResourceManager.GetString("ConsolidatedDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет за месяц.
        /// </summary>
        public static string ConsolidatedMonth {
            get {
                return ResourceManager.GetString("ConsolidatedMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет за неделю.
        /// </summary>
        public static string ConsolidatedWeek {
            get {
                return ResourceManager.GetString("ConsolidatedWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string Creation_Date {
            get {
                return ResourceManager.GetString("Creation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет за день.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать все.
        /// </summary>
        public static string DownloadBtn {
            get {
                return ResourceManager.GetString("DownloadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string FileTableLocation {
            get {
                return ResourceManager.GetString("FileTableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет по безопасности ДЕМО.
        /// </summary>
        public static string GlobalSafetyReport {
            get {
                return ResourceManager.GetString("GlobalSafetyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет файлов.
        /// </summary>
        public static string NoReports {
            get {
                return ResourceManager.GetString("NoReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string OpenBtn {
            get {
                return ResourceManager.GetString("OpenBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть последний.
        /// </summary>
        public static string OpenLatestReport {
            get {
                return ResourceManager.GetString("OpenLatestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оперативная сводка по добыче угля.
        /// </summary>
        public static string OperCoalProductionReport {
            get {
                return ResourceManager.GetString("OperCoalProductionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширеный сводный отчет по шахте.
        /// </summary>
        public static string OverallMineProductionAdvanced {
            get {
                return ResourceManager.GetString("OverallMineProductionAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по добыче УД.
        /// </summary>
        public static string OverallProductionCaption {
            get {
                return ResourceManager.GetString("OverallProductionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводный отчет по шахте.
        /// </summary>
        public static string OveralMineProduction {
            get {
                return ResourceManager.GetString("OveralMineProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статические отчеты.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет контроль качества.
        /// </summary>
        public static string QualityControlReport {
            get {
                return ResourceManager.GetString("QualityControlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string RefreshBtn {
            get {
                return ResourceManager.GetString("RefreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        public static string ReportGeneral {
            get {
                return ResourceManager.GetString("ReportGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип отчета.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по безопасности по объекту ДЕМО .
        /// </summary>
        public static string SiteSafetyReport {
            get {
                return ResourceManager.GetString("SiteSafetyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по скипам.
        /// </summary>
        public static string SkipReport {
            get {
                return ResourceManager.GetString("SkipReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сводные статические отчеты.
        /// </summary>
        public static string StaticConsTitle {
            get {
                return ResourceManager.GetString("StaticConsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по остаткам УД.
        /// </summary>
        public static string StockpilesMonthReport {
            get {
                return ResourceManager.GetString("StockpilesMonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат файла.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчет по вагонным весам.
        /// </summary>
        public static string WagonScalesReport {
            get {
                return ResourceManager.GetString("WagonScalesReport", resourceCulture);
            }
        }
    }
}
