//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMineInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMineInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTS_Analytics.Resources.ResourceMineInfo", typeof(ResourceMineInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь шахтного поля 1584 га. Действовало 4 вертикальных ствола круглого сечения диаметром 6,0—8,5 м, глубиной в 100—552 м. Один из стволов был оборудован скиповым, остальные три — клетевыми подъёмами. В трёх последних осуществляется выдача на поверхность угля, породы, спуск в шахту оборудования, материалов, людей. Для крепления выработок применяли арочную податливую металлическими и деревянными крепями. 
        ///
        ///Протяжённость горных выработок составляла: вертикальных 1,5 км, наклонных — 4,2 км, горизонтальных  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AbayDescr {
            get {
                return ResourceManager.GetString("AbayDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект шахты разработан «Карагандагипрошахт» в 1949 году с проектной мощностью 600 тысяч тонн угля в год. Шахта № 6/7 «Чурубай-Нуринская» сдана в эксплуатацию в 1954 году с годовой проектной мощностью 0,9 млн тонн. В процессе модернизации её мощность была увеличена до 1,5 млн тонн. Добывала коксующиеся и энергетические угли. 
        ///
        ///Приказом Министра угольной промышленности Союза ССР № 313 от 15 июля 1971 года шахта № 6/7 «Чурубай-Нуринская» государственного каменноугольного треста «Абайуголь» была переименован [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AbayHistory {
            get {
                return ResourceManager.GetString("AbayHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта «Абайская» — угледобывающее предприятие угольного департамента компании АО «АрселорМиттал Темиртау». Создана в июле 1998 года путём объединения шахт имени М. И. Калинина (до 1971 — шахта № 9 — Шерубайнуринская) и «Абайская» (до 1971 — шахта № 6—7 Шерубайнуринская). Расположена в городе Абай Карагандинской области, единственная работающая из пяти шахт, существовавших в 1980-х в городе. Входила в состав треста «Абайуголь», в 1970-м вошедшего в состав комбината «Карагандауголь»..
        /// </summary>
        public static string AbayShortDescr {
            get {
                return ResourceManager.GetString("AbayShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Абайская.
        /// </summary>
        public static string AbayTitle {
            get {
                return ResourceManager.GetString("AbayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле шахты расположено в юго-восточной части Тентекского района, являющегося западной окраиной Карагандинского угольного бассейна. Из принятых к отработке пластов Тентекской и Долинской свит в настоящее время шахтой разрабатываются пласты Д10, Д6.
        ///Размеры поля шахты составляют: 
        ///
        ///По простиранию
        ///•	3500-4000 м по пластам Д11-Д1
        ///•	4000-7000 м по пластам Т3-Т1
        ///По падению
        ///•	1600-3150 м по пластам Д11-Д1
        ///•	2500-3900 м по пластам Т3-Т1
        ///Все угли, коксующиеся марки К, КЖ. Основными потребителями углей район [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KazDescr {
            get {
                return ResourceManager.GetString("KazDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта заложена под названием «1/2 Тентекская Вертикальная» в 1957 году, проект разработан институтом «Карагандагипрошахт», руководил строительством инженер Аркадий Матвеевич Фридман. Сдана в эксплуатацию в июне 1969 году с проектной мощностью 2,7 млн тонн угля в год.
        ///Первый директор шахты - Жолумбет Мухамеджанович Мухамеджанов, затем Серсенбай Бектегенович Бектегенов, Вячеслав Анатольевич Стеганов (1980-1987).
        ///В 1971 году переименована в «Казахстанская».
        ///в 1972 году награждена Почётным знаком ЦК КПСС Пре [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KazHistory {
            get {
                return ResourceManager.GetString("KazHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Казахстанская - угольная шахта, расположена в 50 км к юго-западу от Караганды, относится к Карагандинскому угольному бассейну, добываемые марки угля – КЖ, 1К..
        /// </summary>
        public static string KazShortDescr {
            get {
                return ResourceManager.GetString("KazShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Казахстанская.
        /// </summary>
        public static string KazTitle {
            get {
                return ResourceManager.GetString("KazTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размеры шахтного поля составляют:
        ///
        ///
        ///•	по простиранию - 5400 - 9500 метров;
        ///•	по падению - 1500 - 4750 метров.
        ///
        ///
        ///
        ///Площадь горного отвода — 1370 га. Горные работы ведутся на глубине более 840 м на 5-ти рабочих горизонтах, вскрытых 8-ю вертикальными стволами. Протяжённость горных выработок составляет более 100 км. Шахта разрабатывает 8 пластов Карагандинской свиты. 
        ///
        ///Подготовка шахтного поля — этажная, система разработок — длинные столбы по простиранию и по падению. Управление кровлей — полное обруше [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KostDescr {
            get {
                return ResourceManager.GetString("KostDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один из первых руководителей треста «Карагандауголь» Иван Акимович Костенко — посланец Донбасса. В 1933 году начинал строить Новый город, закладывал мощные шахты. В 1934 году трагически погиб. Его имя носит самая крупная шахта Караганды и одна из улиц города. 
        ///
        ///Шахта была заложена 18 мая 1934 года, когда были извлечены первые тонны грунта при закладке шахтного ствола, произведена закладка стволов шахт — «Гигант-А» и «Гигант-Б». 8 мая 1942 года недостроенная шахта была сдана в эксплуатацию. В годы Великой  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KostHistory {
            get {
                return ResourceManager.GetString("KostHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта имени И. А. Костенко — крупнейшее угледобывающее предприятие угольного департамента компании АО «АрселорМиттал Темиртау». Шахта расположена в городе Караганда, Казахстан. В 1980-е годы — одна из крупнейших шахт Карагандинского угольного бассейна. Названа в честь Ивана Акимовича Костенко — одного из освоителей Карагандинского бассейна, управляющий трестом «Карагандауголь»..
        /// </summary>
        public static string KostShortDescr {
            get {
                return ResourceManager.GetString("KostShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта имени Костенко.
        /// </summary>
        public static string KostTitle {
            get {
                return ResourceManager.GetString("KostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория шахты по газу: опасная по внезапным выбросам угля и газа. 
        ///
        ///Метанообильность:
        ///•	Абсолютная м³/мин 154,0.
        ///•	Относительная м³/т 32,0.
        ///Численность работающих (подземная группа), чел.: 1890 (1516). 
        ///
        ///Общая протяжённость горных выработок, км: 75,5. 
        ///
        ///Общая водообильность, м³/час: 230. 
        ///
        ///Максимальная глубина разработки, м: 550. 
        ///
        ///Граница выбросоопасности пластов, м. 
        ///
        ///
        ///•	К10(восточное крыло) — опасный — 450 м.
        ///•	К10(западное крыло) — опасный — 350 м.
        ///•	К7 — угрожаемый — 350 м.
        ///•	К8-7  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KuzDescr {
            get {
                return ResourceManager.GetString("KuzDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технический проект шахты был разработан институтом «Карагандагипрошахт». В 1959 году была сдана в эксплуатацию. В 1971 году шахта № 23 была переименована в «Михайловскую». В 1973 на шахте был установлен всесоюзный рекорд добычи угля — за месяц из 1-й лавы участком № 3 под руководством Отари Ишхнели было добыто 177 тысяч 23 тонны угля. Рекорд продержался 29 лет. В 1979—1981 участок № 1/3, возглавляемый Альбертом Саламатиным (будущий министр промышленности Казахстана и отец экс-министра обороны Украины Дмитри [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KuzHistory {
            get {
                return ResourceManager.GetString("KuzHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ордена Трудового Красного Знамени шахта имени Туспа Кузембева (до 1971 — шахта № 23, в 1971—1982 — «Михайловская», с 1982 — современное название) — угледобывающее предприятие угольного департамента компании АО «АрселорМиттал Темиртау». Расположена в городе Сарани Карагандинской области. Входила в состав треста «Сараньуголь», в 1970-м вошедшего в состав комбината «Карагандауголь». В 1970-х и 1980-х годах неоднократный рекордсмен по добыче угля.
        /// </summary>
        public static string KuzShortDescr {
            get {
                return ResourceManager.GetString("KuzShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта имени Кузембаева.
        /// </summary>
        public static string KuzTitle {
            get {
                return ResourceManager.GetString("KuzTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На шахте имени Ленина ведётся добыча коксующихся углей марок К, Ж и КЖ. Опасна по внезапным выбросам угля, метана и взрывчатости угольной пыли. Шахтное поле вскрыто 4 вертикальными и 1 наклонным стволами сечением в свету 7—28,3 м² и 12,8 м². Разрабатываются пласты d6 (мощность пласта — 5,5 м) и d10 (2,4 м), отработка которого ведётся в один слой, пласт d6 отрабатывается в два слоя, по схеме «пласт — слой».
        ///
        ///
        ///Выемка угля производится механизированными комплексами типа «Глиник» (комбайн 2ГШ-68 Б), 2ОКП-70  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LenDescr {
            get {
                return ResourceManager.GetString("LenDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Технический проект шахты был разработан институтом «Карагандагипрошахт». В 1958 состоялась закладка шахты, а в 1964 году она была сдана в эксплуатацию. Проектная мощность составляла 1200 тысяч тонн угля в год. Тогда же, для централизованного отопления стволов шахт и снабжения их электроэнергией была построена Тентекская ТЭЦ. В 1968 году объединена с шахтой № 1/2 «Наклонная». В 1969 был пересмотрен технический проект второго горизонта, в результате чего годовая мощность шахты достигла 3200 тысяч тонн угля.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LenHistory {
            get {
                return ResourceManager.GetString("LenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ордена Трудового Красного Знамени шахта имени В. И. Ленина (до 1971 — шахта № 3 — Тентекская) — угледобывающее предприятие угольного департамента компании АО «АрселорМиттал Темиртау». Расположена в городе Шахтинске Карагандинской области. В 1980-е годы — одна из крупнейших шахт Карагандинского угольного бассейна. Входила в состав треста «Шахтинскуголь», в 1970-м вошедшего в состав комбината «Карагандауголь»..
        /// </summary>
        public static string LenShortDescr {
            get {
                return ResourceManager.GetString("LenShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта имени Ленина.
        /// </summary>
        public static string LenTitle {
            get {
                return ResourceManager.GetString("LenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахтное поле площадью 11,3 км2 вскрыто 5 вертикальными стволами глубиной 454—520 м, 3 из которых оборудованы скиповыми и клетевыми подъемными установками для выдачи на поверхность угля, породы и спуска в шахту оборудования, материалов и людей. 
        ///
        ///Схема подготовки шахтного поля этажная, система разработки длинными столбами по простиранию. Добыча угля осуществляется комплексно механизированным способом. Для отработки лав используются механизированные комплексы типа УКП-5, 2КМ144 с очистными комбайнами SL-300 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SarDescr {
            get {
                return ResourceManager.GetString("SarDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта «Саранская» (до 1971 шахта № 120) — угледобывающее предприятие в г. Сарань Карагандинской области Казахстана. С 1996 года входит в состав угольного департамента АО «АрселорМиттал Темиртау». 
        ///История
        ///
        ///Шахта «Саранская» сдана в эксплуатацию 31 декабря 1955 года с проектной мощностью 900 тыс. т угля в год. После реконструкции в 1975 мощность возросла до 1,5 млн т. Первым начальником шахты был назначен Петр Семенович Пиксимов. В течение первого квартала 1956 года коллектив шахты устранял недодел­ки на  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SarHistory {
            get {
                return ResourceManager.GetString("SarHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта «Саранская» (до 1971 шахта № 120) — угледобывающее предприятие в г. Сарань Карагандинской области Казахстана. С 1996 года входит в состав угольного департамента АО «АрселорМиттал Темиртау»..
        /// </summary>
        public static string SarShortDescr {
            get {
                return ResourceManager.GetString("SarShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Саранская.
        /// </summary>
        public static string SarTitle {
            get {
                return ResourceManager.GetString("SarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добываемые марки угля – Ж, КО, КЖ. 
        ///
        ///Отрабатываемые пласты Д6, Д1-2. 
        ///
        ///Объемы добычи угля в 2010 году составили 900 тыс. тонн..
        /// </summary>
        public static string ShahDescr {
            get {
                return ResourceManager.GetString("ShahDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В настоящее время на шахте применяется система разработки длинными столбами по простиранию и падению. Отработка выемочных полей по пласту Д1-2 осуществляется механизированым комплексом «Глиник 15-29У», выемка угля осуществляется очистным комбайном SL-300, транспортировка угля осуществляется по очистному забою конвейером КС-34, по конвейерному штреку перегружателем ПС-34 производится погрузка на ленточные конвейера типа 3ЛКР-1000 и 2ЛКР-1000, далее по ленточным конвейерам на скиповой подъем, по скиповому под [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShahHistory {
            get {
                return ResourceManager.GetString("ShahHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта «Шахтинская» — угледобывающее предприятие в г. Шахтинск Карагандинской области Казахстана. Входит в состав угольного департамента АО «Арселор Миттал Темиртау». 
        ///
        ///Шахта сдана в эксплуатацию в 1973 году с годовой проектной мощностью 1,8 млн тонн. После начала эксплуатации шахты был выполнен проект вскрытия и подготовки северного и восточного блоков пластов Д7 и Д6, по которому мощность шахты увеличена до 2,4 млн тонн в год..
        /// </summary>
        public static string ShahShortDescr {
            get {
                return ResourceManager.GetString("ShahShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Шахтинская.
        /// </summary>
        public static string ShahTitle {
            get {
                return ResourceManager.GetString("ShahTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В пределах границ шахтного поля залегают 10 пластов «Тентекской» и «Долинской» свит, которые по степени сближённости делятся на 4 группы:
        ///•	1 группа — пласты «Тентекской» свиты Т3 и Т1
        ///•	2 группа — пласты «Долинской» свиты Д11, Д10, Д9
        ///•	3 группа — пласты «Долинской» свиты Д7 и Д6
        ///•	4 группа — пласты «Долинской» свиты Д5,Д4 и Д1.
        ///
        ///Крупные разрывные нарушения — Шаханский взбросо-сдвиг (Н=40-430), взброс 14(Н=20-250) и взброс 5 (Н=10-65) разделяют поле на три блока: Северный, Центральный и Южный. 
        ///
        ///Ша [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TentDescr {
            get {
                return ResourceManager.GetString("TentDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TentHistory {
            get {
                return ResourceManager.GetString("TentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта «Тентекская» — угледобывающее предприятие в г. Шахтинск Карагандинской области Казахстана. Входит в состав угольного департамента АО «Арселор Миттал Темиртау». 
        ///
        ///Сдана в эксплуатацию в 1979 году. Название получила по речке Тентек протекавшей рядом. Имела также номерное название, иногда упоминается как «восьмая» шахта. 
        ///
        ///Поле шахты «Тентекская» находится в северо-восточной части Тентекского угленосного района Карагандинского бассейна, в 50 км к западу от г. Караганды. Размеры поля составляют: по пр [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TentShortDescr {
            get {
                return ResourceManager.GetString("TentShortDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шахта Тентекская.
        /// </summary>
        public static string TentTitle {
            get {
                return ResourceManager.GetString("TentTitle", resourceCulture);
            }
        }
    }
}
